version: '3.8'
services:
  ngomong-online:
    container_name: ngomong-online
    build: ./ngomong.online/
    image: ngomong-online:2.0
    ports:
      - 80:5000
    depends_on:
      - mongo_seed
    environment:
      - NAME=Docker
      - MONGO_HOST=mongo_seed
      - MONGO_PORT=27017
    networks:
      - ngomong_network
  mongo_seed:
    container_name: mongo_seed
    image: mongo:4.0.16-xenial
    ports: 
      - 27017:27017
    networks:
      - ngomong_network
    volumes:
    - ./import.sh:/docker-entrypoint-initdb.d/import.sh
    - ./mainDB:/mainDB
      
networks:
  ngomong_network:
    name: ngomong_network
